apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: ruby-docker-app-openshift
  name: ruby-docker-app-openshift
spec:
  dockerImageRepository: "rhscl/ruby-25-rhel7"
spec:
  source:
    type: Git
    git:
      uri: https://github.com/abuzitos/ruby-docker-app.git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile.groovy
